# Generated by Django 5.1.8 on 2025-05-16 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Description of the survey.')),
                ('configuration', models.TextField(help_text='Configuration of the survey in suveyjs JSON format.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when the survey was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time when the survey was last updated.')),
                ('strategy', models.CharField(blank=True, default='', max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the survey is active or not.')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(help_text='Response to the survey in suveyjs JSON format.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when the response was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time when the response was last updated.')),
                ('ip_address', models.CharField(blank=True, default='', help_text='IP address of the user who submitted the response.')),
                ('report_file', models.FileField(blank=True, help_text='File containing the report of the survey response.', null=True, upload_to='reports/%Y/%m/%d/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(help_text='Survey to which the response belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['-id'],
            },
        ),
    ]
