# Generated by Django 5.1.8 on 2025-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Price of the survey.', max_digits=10),
        ),
    ]
